apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: product-specification-badges
  description: Use this component to show badges based on your product
    specifications inside your product page.
  tags:
    - typescript
    - react:16
  annotations:
    vtex.com/janus-acronym: ""
    vtex.com/o11y-os-index: ""
    grafana/dashboard-selector: ""
    github.com/project-slug: vtex-apps/product-specification-badges
    vtex.com/platform-flow-id: ""
    backstage.io/techdocs-ref: dir:../
    vtex.com/application-id: YB78RB74
spec:
  system: store-framework-ui-apps
  lifecycle: stable
  owner: te-0013
  type: frontend-ui
  dependsOn: []
  subcomponentOf: store-framework
